### ISSUE TITLE
URL を決める

### ISSUE THREAD

**Issue by hanamura** [hanamura/chofu-space#3]
@MasatoshiTabuchi @HirokazuMatsuda 
どうしよう？

**Comment by HirokazuMatsuda** [comment]
![スクリーンショット 2020-12-01 15 25 58](https://user-images.githubusercontent.com/75295994/100704841-88c5e800-33e9-11eb-8067-544e075063f6.png)

**Comment by hanamura** [comment]
@MasatoshiTabuchi @HirokazuMatsuda 
Google Domains とかで取得してもらえると良いような気がしている。
https://domains.google/intl/ja_jp/

**Comment by HirokazuMatsuda** [comment]
![スクリーンショット 2020-12-01 15 27 42](https://user-images.githubusercontent.com/75295994/100704967-c6c30c00-33e9-11eb-8a5a-ed4285682120.png)

**Comment by HirokazuMatsuda** [comment]
![スクリーンショット 2020-12-01 15 28 55](https://user-images.githubusercontent.com/75295994/100705066-f1ad6000-33e9-11eb-9c42-2b7d9be95ac8.png)

**Comment by HirokazuMatsuda** [comment]
ハイフンなしにします？

**Comment by hanamura** [comment]
@MasatoshiTabuchi @HirokazuMatsuda 
取得ありがとうございます！
https://chofu-space.info になりました 🎉
